[book]
authors = ["pietrocipriani"]
language = "in"
multilingual = false
src = "src"
title = "Palestra di Algoritmi"

[output.html]
mathjax-support = true

[build]
build-dir = "../docs"
create-missing = false
