[book]
authors = ["pietrocipriani"]
language = "in"
multilingual = false
src = "src"
title = "Palestra di Algoritmi"

[output.html]
mathjax-support = true
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true
level = 0

[build]
build-dir = "../docs"
create-missing = false
